# CircleCI build configuration file
version: 2
jobs:
  build:
    docker:
      - image: sethuster/circlebuild

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker build
          command: docker build -t sethuster/circlebuild .
      - run:
          name: Push to Docker hub
          command: |
            docker push sethuster/circlebuild:latest

  smoketest-dev:
    docker:
      - image: sethuster/circlebranch:latest

    steps:
      - run:
          name: Run smoke test
          command: |
            cd /testapp
            sudo npm run d_test

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
                
  smoketest-dev:
    triggers:
      - schedule:
          # Run tests 20 min past the hour
          cron: "20 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - smoketest-dev

